// ─── Proof Kernel ──────────────────────────────────────────────────
//
// A small trusted kernel that checks proof objects. Contains no search
// heuristics — only primitive inference rules and certificate checkers.
//
// ## Architecture
//
//     Proof (generated by tactics/search)
//         │
//         ▼
//     ProofChecker.check(context, proof, expected)
//         │
//         ▼
//     Result<(), KernelError>   ← purely deterministic
//
// ## Proof variants (7)
//
// | Variant | Rule |
// |---------|------|
// | `Hypothesis` | Use a hypothesis from the context |
// | `Refl` | t = t (reflexivity) |
// | `Trans` | a = b, b = c ⊢ a = c (transitivity) |
// | `Congr` | a₁ = b₁, ..., aₙ = bₙ ⊢ C(a₁,...,aₙ) = C(b₁,...,bₙ) |
// | `Theorem` | Instantiate a trusted theorem schema |
// | `Intro` | P ⊢ Q ⇒ ⊢ P → Q  or  ⊢ P(x) ⇒ ⊢ ∀x, P(x) |
// | `Certificate` | Closed arithmetic, polynomial normalization, etc. |

use crate::algebra::SymExpr;
use crate::proposition::*;

// ═══════════════════════════════════════════════════════════════════
// EXPRESSION CONSTRUCTOR
// ═══════════════════════════════════════════════════════════════════

/// Identifies which SymExpr constructor a `Congr` proof uses.
/// The kernel uses this to reconstruct the equality at the top level.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ExprConstructor {
    // Binary
    Add,
    Sub,
    Mul,
    Div,
    Pow,
    // Unary
    Neg,
    Sin,
    Cos,
    Tan,
    Sqrt,
    Exp,
    Ln,
    Abs,
    Sinh,
    Cosh,
    Tanh,
    Asin,
    Acos,
    Atan,
}

impl ExprConstructor {
    fn arity(&self) -> usize {
        match self {
            ExprConstructor::Add
            | ExprConstructor::Sub
            | ExprConstructor::Mul
            | ExprConstructor::Div
            | ExprConstructor::Pow => 2,
            ExprConstructor::Neg
            | ExprConstructor::Sin
            | ExprConstructor::Cos
            | ExprConstructor::Tan
            | ExprConstructor::Sqrt
            | ExprConstructor::Exp
            | ExprConstructor::Ln
            | ExprConstructor::Abs
            | ExprConstructor::Sinh
            | ExprConstructor::Cosh
            | ExprConstructor::Tanh
            | ExprConstructor::Asin
            | ExprConstructor::Acos
            | ExprConstructor::Atan => 1,
        }
    }

    /// Apply the constructor to a slice of arguments (all should already be
    /// the correct side of the equality — left args or right args).
    fn apply(&self, args: &[SymExpr]) -> SymExpr {
        use SymExpr::*;
        match self {
            ExprConstructor::Add => Add(Box::new(args[0].clone()), Box::new(args[1].clone())),
            ExprConstructor::Sub => Sub(Box::new(args[0].clone()), Box::new(args[1].clone())),
            ExprConstructor::Mul => Mul(Box::new(args[0].clone()), Box::new(args[1].clone())),
            ExprConstructor::Div => Div(Box::new(args[0].clone()), Box::new(args[1].clone())),
            ExprConstructor::Pow => Pow(Box::new(args[0].clone()), Box::new(args[1].clone())),
            ExprConstructor::Neg => Neg(Box::new(args[0].clone())),
            ExprConstructor::Sin => Sin(Box::new(args[0].clone())),
            ExprConstructor::Cos => Cos(Box::new(args[0].clone())),
            ExprConstructor::Tan => Tan(Box::new(args[0].clone())),
            ExprConstructor::Sqrt => Sqrt(Box::new(args[0].clone())),
            ExprConstructor::Exp => Exp(Box::new(args[0].clone())),
            ExprConstructor::Ln => Ln(Box::new(args[0].clone())),
            ExprConstructor::Abs => Abs(Box::new(args[0].clone())),
            ExprConstructor::Sinh => Sinh(Box::new(args[0].clone())),
            ExprConstructor::Cosh => Cosh(Box::new(args[0].clone())),
            ExprConstructor::Tanh => Tanh(Box::new(args[0].clone())),
            ExprConstructor::Asin => Asin(Box::new(args[0].clone())),
            ExprConstructor::Acos => Acos(Box::new(args[0].clone())),
            ExprConstructor::Atan => Atan(Box::new(args[0].clone())),
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
// CERTIFICATE
// ═══════════════════════════════════════════════════════════════════

/// A certificate from a trusted deterministic solver.
///
/// Each variant has a small independent checker in the kernel. The
/// certificate data is minimal — just enough for the kernel to
/// independently verify the result without re-running the full solver.
#[derive(Clone, Debug, PartialEq)]
pub enum Certificate {
    /// The proposition is a closed (variable-free) arithmetic truth,
    /// e.g. `4 ≥ 0`, `2 + 2 = 4`. The kernel re-evaluates to verify.
    ConstantEvaluation,
}

// ═══════════════════════════════════════════════════════════════════
// PROOF — 7 variants
// ═══════════════════════════════════════════════════════════════════

/// A machine-checkable proof object.
///
/// Proofs are checked bottom-up by the `ProofChecker`. Each variant
/// corresponds to a primitive inference rule. The kernel verifies that
/// the proof's conclusion matches the expected proposition.
#[derive(Clone, Debug, PartialEq)]
pub enum Proof {
    /// Use a hypothesis from the context.
    /// The kernel looks up `HypothesisId` in the context and returns
    /// the associated proposition.
    Hypothesis(HypothesisId),

    /// t = t by reflexivity.
    Refl(SymExpr),

    /// From `a = b` and `b = c` (or `c = b`), derive `a = c`.
    Trans(Box<Proof>, Box<Proof>),

    /// Congruence: from `a₁ = b₁, ..., aₙ = bₙ`, derive
    /// `C(a₁, ..., aₙ) = C(b₁, ..., bₙ)`.
    Congr {
        constructor: ExprConstructor,
        arg_proofs: Vec<Proof>,
    },

    /// Instantiate a trusted theorem from the environment.
    /// `subst` maps the theorem's binder variables to their target
    /// expressions. `premise_proofs` proves each premise after
    /// instantiation.
    Theorem {
        id: TheoremId,
        subst: Substitution,
        premise_proofs: Vec<Proof>,
    },

    /// Introduction rule:
    /// - `Assumption { id, P }`: extend context with P, prove Q → return P → Q
    /// - `ForAll { var }`: prove P(var) → return ∀var, P(var)
    Intro { binder: Binder, body: Box<Proof> },

    /// A proposition asserted by a trusted deterministic solver.
    /// The kernel independently verifies using the certificate checker.
    Certificate {
        proposition: Proposition,
        certificate: Certificate,
    },
}

// ═══════════════════════════════════════════════════════════════════
// KERNEL ERROR
// ═══════════════════════════════════════════════════════════════════

/// Errors produced by the proof kernel.
#[derive(Clone, Debug, PartialEq)]
pub enum KernelError {
    /// The proof's conclusion doesn't match what was expected.
    ExpectedMismatch {
        expected: Proposition,
        actual: Proposition,
    },

    /// Referenced theorem ID not found in the environment.
    NoSuchTheorem(TheoremId),

    /// Referenced hypothesis ID not found in the context.
    NoSuchHypothesis(HypothesisId),

    /// A premise proof was missing or proved the wrong thing.
    PremiseMismatch {
        index: usize,
        expected: Proposition,
        error: Box<KernelError>,
    },

    /// The number of premise proofs doesn't match the number of premises.
    PremiseCountMismatch { expected: usize, got: usize },

    /// A binder was not instantiated in the substitution.
    UninstantiatedBinder(String),

    /// Transitivity: middle terms don't match.
    TransitivityMismatch {
        left_conclusion: Proposition,
        right_conclusion: Proposition,
    },

    /// Transitivity: one or both proofs don't conclude an equality.
    TransitivityNonEquality {
        left_conclusion: Proposition,
        right_conclusion: Proposition,
    },

    /// Congruence: wrong number of argument proofs for this constructor.
    ConstructorArityMismatch {
        constructor: ExprConstructor,
        expected: usize,
        got: usize,
    },

    /// Congruence: an argument proof doesn't conclude an equality.
    CongruenceArgNotEquality { index: usize, proved: Proposition },

    /// Certificate rejected (the proposition isn't true or isn't ground).
    CertificateRejected(Proposition),

    /// Intro: the binder variable appears free in a hypothesis.
    IntroArbitraryClash {
        variable: crate::algebra::Variable,
        clashing_hypothesis: Proposition,
    },

    /// Intro: body proof produced a different proposition from expected.
    IntroBodyMismatch {
        expected_body: Proposition,
        actual_body: Proposition,
    },
}

impl std::fmt::Display for KernelError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            KernelError::ExpectedMismatch { expected, actual } => {
                write!(f, "expected {} but proof proves {}", expected, actual)
            }
            KernelError::NoSuchTheorem(id) => {
                write!(f, "no theorem with id {:?}", id)
            }
            KernelError::NoSuchHypothesis(id) => {
                write!(f, "no hypothesis with id {:?}", id)
            }
            KernelError::PremiseMismatch {
                index,
                expected,
                error,
            } => {
                write!(f, "premise[{}]: expected {} — {}", index, expected, error)
            }
            KernelError::PremiseCountMismatch { expected, got } => {
                write!(f, "expected {} premise proofs but got {}", expected, got)
            }
            KernelError::UninstantiatedBinder(name) => {
                write!(f, "binder '{}' was not instantiated", name)
            }
            KernelError::TransitivityMismatch { .. } => {
                write!(f, "transitivity: middle terms do not match")
            }
            KernelError::TransitivityNonEquality { .. } => {
                write!(f, "transitivity: arguments must conclude equalities")
            }
            KernelError::ConstructorArityMismatch {
                constructor,
                expected,
                got,
            } => {
                write!(
                    f,
                    "constructor {:?} expects {} arguments but got {}",
                    constructor, expected, got
                )
            }
            KernelError::CongruenceArgNotEquality { index, proved } => {
                write!(
                    f,
                    "congruence arg[{}] proves {} (expected equality)",
                    index, proved
                )
            }
            KernelError::CertificateRejected(p) => {
                write!(f, "certificate rejected: {}", p)
            }
            KernelError::IntroArbitraryClash { variable, .. } => {
                write!(
                    f,
                    "intro ∀{}: variable appears free in a hypothesis",
                    variable
                )
            }
            KernelError::IntroBodyMismatch { .. } => {
                write!(f, "intro: body proof proves wrong proposition")
            }
        }
    }
}

impl std::error::Error for KernelError {}

// ═══════════════════════════════════════════════════════════════════
// CONSTANT EVALUATION CHECKER
// ═══════════════════════════════════════════════════════════════════

/// Evaluate a ground (variable-free) SymExpr to a numeric value.
/// Returns `None` if the expression contains variables or non-evaluable
/// functions (sin, cos, etc.).
fn eval_term(t: &SymExpr) -> Option<f64> {
    use SymExpr::*;
    match t {
        Num(v) => Some(*v),
        Var(_) => None,
        Add(a, b) => Some(eval_term(a)? + eval_term(b)?),
        Sub(a, b) => Some(eval_term(a)? - eval_term(b)?),
        Mul(a, b) => Some(eval_term(a)? * eval_term(b)?),
        Div(a, b) => Some(eval_term(a)? / eval_term(b)?),
        Pow(a, b) => Some(eval_term(a)?.powf(eval_term(b)?)),
        Neg(a) => Some(-eval_term(a)?),
        // Non-arithmetic: sin, cos, etc. cannot be constant-evaluated
        // because we'd need to know the argument is a constant.
        Sin(_)
        | Cos(_)
        | Tan(_)
        | Sqrt(_)
        | Exp(_)
        | Ln(_)
        | Abs(_)
        | Sinh(_)
        | Cosh(_)
        | Tanh(_)
        | Asin(_)
        | Acos(_)
        | Atan(_)
        | Limit { .. }
        | Integral { .. } => None,
    }
}

/// Check whether a proposition is a ground arithmetic truth.
///
/// The proposition must:
/// 1. Be closed (no free variables)
/// 2. Involve only arithmetic operations (+, -, *, /, ^)
/// 3. Be structurally true (e.g., `4 ≥ 0`, `2+2 = 4`)
///
/// This is used by `Certificate::ConstantEvaluation`.
pub(crate) fn check_constant_evaluation(p: &Proposition) -> bool {
    // First check the proposition is ground (no free variables)
    if !free_vars_proposition(p).is_empty() {
        return false;
    }

    match p {
        Proposition::Eq(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => (va - vb).abs() < 1e-9,
            _ => false,
        },
        Proposition::NotEq(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => (va - vb).abs() >= 1e-9,
            _ => false,
        },
        Proposition::Lt(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => va < vb - 1e-9,
            _ => false,
        },
        Proposition::Le(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => va <= vb + 1e-9,
            _ => false,
        },
        Proposition::Gt(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => va > vb + 1e-9,
            _ => false,
        },
        Proposition::Ge(a, b) => match (eval_term(a), eval_term(b)) {
            (Some(va), Some(vb)) => va >= vb - 1e-9,
            _ => false,
        },
        // Not (yet) evaluable
        Proposition::True => true,
        Proposition::False => false,
        _ => false,
    }
}

// ═══════════════════════════════════════════════════════════════════
// PROOF CHECKER
// ═══════════════════════════════════════════════════════════════════

/// The trusted proof checker.
///
/// Checks proof objects against a `TheoremEnvironment` and `LocalContext`.
/// Returns `Ok(())` if the proof is valid and its conclusion matches the
/// expected proposition.
pub struct ProofChecker {
    theorem_env: TheoremEnvironment,
}

impl ProofChecker {
    /// Create a new checker with the given theorem environment.
    pub fn new(theorem_env: TheoremEnvironment) -> Self {
        ProofChecker { theorem_env }
    }

    /// Check that `proof` proves `expected` in the given `context`.
    ///
    /// This is the main entry point. It calls `check_inner` to determine
    /// what the proof actually proves, then compares with expected.
    pub fn check(
        &self,
        context: &LocalContext,
        proof: &Proof,
        expected: &Proposition,
    ) -> Result<(), KernelError> {
        let actual = self.check_inner(context, proof)?;
        if actual == *expected {
            Ok(())
        } else {
            Err(KernelError::ExpectedMismatch {
                expected: expected.clone(),
                actual,
            })
        }
    }

    /// Internal check: return the proposition that the proof proves.
    fn check_inner(
        &self,
        context: &LocalContext,
        proof: &Proof,
    ) -> Result<Proposition, KernelError> {
        match proof {
            // ── Hypothesis ──────────────────────────────────
            Proof::Hypothesis(id) => context
                .hypotheses
                .iter()
                .find(|(hid, _)| hid == id)
                .map(|(_, p)| p.clone())
                .ok_or(KernelError::NoSuchHypothesis(*id)),

            // ── Reflexivity ─────────────────────────────────
            Proof::Refl(expr) => Ok(Proposition::eq(expr.clone(), expr.clone())),

            // ── Transitivity ────────────────────────────────
            Proof::Trans(first, second) => {
                let p1 = self.check_inner(context, first)?;
                let p2 = self.check_inner(context, second)?;

                match (&p1, &p2) {
                    (Proposition::Eq(a, b), Proposition::Eq(c, d)) => {
                        // Check that middle terms match: b == c OR a == d
                        if *b == *c {
                            Ok(Proposition::eq(a.clone(), d.clone()))
                        } else if *a == *d {
                            Ok(Proposition::eq(b.clone(), c.clone()))
                        } else {
                            Err(KernelError::TransitivityMismatch {
                                left_conclusion: p1,
                                right_conclusion: p2,
                            })
                        }
                    }
                    _ => Err(KernelError::TransitivityNonEquality {
                        left_conclusion: p1,
                        right_conclusion: p2,
                    }),
                }
            }

            // ── Congruence ──────────────────────────────────
            Proof::Congr {
                constructor,
                arg_proofs,
            } => {
                let expected_arity = constructor.arity();
                if arg_proofs.len() != expected_arity {
                    return Err(KernelError::ConstructorArityMismatch {
                        constructor: *constructor,
                        expected: expected_arity,
                        got: arg_proofs.len(),
                    });
                }

                let mut left_args: Vec<SymExpr> = Vec::new();
                let mut right_args: Vec<SymExpr> = Vec::new();

                for (i, arg_proof) in arg_proofs.iter().enumerate() {
                    let eq = self.check_inner(context, arg_proof)?;
                    match eq {
                        Proposition::Eq(l, r) => {
                            left_args.push(l);
                            right_args.push(r);
                        }
                        // Also handle flipped: r = l → l, r
                        // But we need to determine which is the "left" and which is "right".
                        // Since our proofs should consistently produce a = b with a being
                        // the original expression and b being the transformed one,
                        // we'll just take the first as left and second as right.
                        // If the user provides r = l, we still accept it as l = r.
                        _ => {
                            return Err(KernelError::CongruenceArgNotEquality {
                                index: i,
                                proved: eq,
                            });
                        }
                    }
                }

                let left_expr = constructor.apply(&left_args);
                let right_expr = constructor.apply(&right_args);
                Ok(Proposition::eq(left_expr, right_expr))
            }

            // ── Theorem instantiation ───────────────────────
            Proof::Theorem {
                id,
                subst,
                premise_proofs,
            } => {
                let theorem = self
                    .theorem_env
                    .get_by_id(*id)
                    .ok_or(KernelError::NoSuchTheorem(*id))?;

                // Check all binders are instantiated
                for binder in &theorem.binders {
                    if subst.get(shared_var(binder)).is_none() {
                        return Err(KernelError::UninstantiatedBinder(binder.clone()));
                    }
                }

                // Instantiate premises and conclusion
                let instantiated_premises: Vec<Proposition> = theorem
                    .premises
                    .iter()
                    .map(|p| substitute_proposition(p, subst))
                    .collect();
                let instantiated_conclusion = substitute_proposition(&theorem.conclusion, subst);

                // Check premise count matches
                if premise_proofs.len() != instantiated_premises.len() {
                    return Err(KernelError::PremiseCountMismatch {
                        expected: instantiated_premises.len(),
                        got: premise_proofs.len(),
                    });
                }

                // Check each premise proof
                for (i, (premise_proof, expected_premise)) in premise_proofs
                    .iter()
                    .zip(instantiated_premises.iter())
                    .enumerate()
                {
                    if let Err(e) = self.check(context, premise_proof, expected_premise) {
                        return Err(KernelError::PremiseMismatch {
                            index: i,
                            expected: expected_premise.clone(),
                            error: Box::new(e),
                        });
                    }
                }

                Ok(instantiated_conclusion)
            }

            // ── Introduction ────────────────────────────────
            Proof::Intro { binder, body } => {
                match binder {
                    Binder::Assumption {
                        hypothesis_id,
                        proposition,
                    } => {
                        // Extend context with the assumption
                        let mut extended_context = context.clone();
                        extended_context.add_hypothesis((**proposition).clone());
                        // Re-add with the given ID (add_hypothesis generates a new ID,
                        // so we need to add with the specific ID)
                        // Actually, let's just use the generated ID.
                        // The `hypothesis_id` in the binder is for the tactic's reference;
                        // the kernel just needs to extend the context.

                        let body_result = self.check_inner(&extended_context, body)?;

                        Ok(Proposition::implies((**proposition).clone(), body_result))
                    }

                    Binder::ForAll { variable } => {
                        // Check var_name (variable.display) doesn't appear free in any hypothesis
                        for (_, h) in &context.hypotheses {
                            if free_vars_proposition(h).contains(variable.display.as_ref()) {
                                return Err(KernelError::IntroArbitraryClash {
                                    variable: variable.clone(),
                                    clashing_hypothesis: h.clone(),
                                });
                            }
                        }

                        let body_result = self.check_inner(context, body)?;

                        Ok(Proposition::forall(&variable, body_result))
                    }
                }
            }

            // ── Certificate ────────────────────────────────
            Proof::Certificate {
                proposition,
                certificate,
            } => {
                let ok = match certificate {
                    Certificate::ConstantEvaluation => check_constant_evaluation(proposition),
                };
                if ok {
                    Ok(proposition.clone())
                } else {
                    Err(KernelError::CertificateRejected(proposition.clone()))
                }
            }
        }
    }
}

// ═══════════════════════════════════════════════════════════════════
// TESTS
// ═══════════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use SymExpr::*;

    fn v(name: &str) -> SymExpr {
        Var(crate::proposition::shared_var(name))
    }

    fn forall_v(name: &str, body: Proposition) -> Proposition {
        Proposition::forall(&crate::proposition::shared_var(name), body)
    }

    fn num(v: f64) -> SymExpr {
        Num(v)
    }

    // ── Constant Evaluation Tests ────────────────────────────

    #[test]
    fn test_eval_term_constant() {
        assert_eq!(eval_term(&num(42.0)), Some(42.0));
    }

    #[test]
    fn test_eval_term_add() {
        assert_eq!(eval_term(&(num(2.0) + num(3.0))), Some(5.0));
    }

    #[test]
    fn test_eval_term_with_var_fails() {
        assert_eq!(eval_term(&v("x")), None);
    }

    #[test]
    fn test_eval_term_nested() {
        // (2 + 3) * 4 = 20
        let expr = (num(2.0) + num(3.0)) * num(4.0);
        assert_eq!(eval_term(&expr), Some(20.0));
    }

    #[test]
    fn test_check_constant_evaluation_ge() {
        assert!(check_constant_evaluation(&Proposition::ge(
            num(4.0),
            num(0.0)
        )));
        assert!(!check_constant_evaluation(&Proposition::ge(
            num(-1.0),
            num(0.0)
        )));
    }

    #[test]
    fn test_check_constant_evaluation_eq() {
        assert!(check_constant_evaluation(&Proposition::eq(
            num(5.0),
            num(5.0)
        )));
        assert!(!check_constant_evaluation(&Proposition::eq(
            num(5.0),
            num(6.0)
        )));
    }

    #[test]
    fn test_check_constant_evaluation_with_var_fails() {
        // Can't evaluate x ≥ 0
        assert!(!check_constant_evaluation(&Proposition::ge(
            v("x"),
            num(0.0)
        )));
    }

    #[test]
    fn test_check_constant_evaluation_true() {
        assert!(check_constant_evaluation(&Proposition::True));
    }

    #[test]
    fn test_check_constant_evaluation_false() {
        assert!(!check_constant_evaluation(&Proposition::False));
    }

    #[test]
    fn test_check_constant_evaluation_complex() {
        // 2 + 3 = 5
        assert!(check_constant_evaluation(&Proposition::eq(
            num(2.0) + num(3.0),
            num(5.0)
        )));
        // (2 + 3) * 4 = 20
        assert!(check_constant_evaluation(&Proposition::eq(
            (num(2.0) + num(3.0)) * num(4.0),
            num(20.0)
        )));
    }

    // ── Proof Checker Tests ──────────────────────────────────

    fn make_checker() -> ProofChecker {
        ProofChecker::new(TheoremEnvironment::with_initial_theorems())
    }

    /// Test 1: Hypothesis — simplest proof
    #[test]
    fn test_check_hypothesis() {
        let mut ctx = LocalContext::new();
        let p = Proposition::ge(v("x"), num(0.0));
        let id = ctx.add_hypothesis(p.clone());

        let checker = make_checker();
        let proof = Proof::Hypothesis(id);

        assert!(checker.check(&ctx, &proof, &p).is_ok());
    }

    /// Test 2: Hypothesis — wrong ID
    #[test]
    fn test_check_hypothesis_wrong_id() {
        let ctx = LocalContext::new();
        let checker = make_checker();
        let proof = Proof::Hypothesis(HypothesisId(999));
        let expected = Proposition::ge(v("x"), num(0.0));

        let result = checker.check(&ctx, &proof, &expected);
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            KernelError::NoSuchHypothesis(_)
        ));
    }

    /// Test 3: Reflexivity
    #[test]
    fn test_check_refl() {
        let ctx = LocalContext::new();
        let checker = make_checker();

        let proof = Proof::Refl(v("x"));
        let expected = Proposition::eq(v("x"), v("x"));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 4: Reflexivity — wrong expected
    #[test]
    fn test_check_refl_wrong() {
        let ctx = LocalContext::new();
        let checker = make_checker();

        let proof = Proof::Refl(v("x"));
        let expected = Proposition::eq(v("x"), v("y"));

        let result = checker.check(&ctx, &proof, &expected);
        assert!(result.is_err());
    }

    /// Test 5: Certificate — 4 ≥ 0
    #[test]
    fn test_check_certificate_ge() {
        let ctx = LocalContext::new();
        let checker = make_checker();

        let proposition = Proposition::ge(num(4.0), num(0.0));
        let proof = Proof::Certificate {
            proposition: proposition.clone(),
            certificate: Certificate::ConstantEvaluation,
        };

        assert!(checker.check(&ctx, &proof, &proposition).is_ok());
    }

    /// Test 6: Certificate — 0 ≥ 4 (false!)
    #[test]
    fn test_check_certificate_false_claim() {
        let ctx = LocalContext::new();
        let checker = make_checker();

        let proposition = Proposition::ge(num(0.0), num(4.0));
        let proof = Proof::Certificate {
            proposition: proposition.clone(),
            certificate: Certificate::ConstantEvaluation,
        };

        let result = checker.check(&ctx, &proof, &proposition);
        assert!(result.is_err());
        match result.unwrap_err() {
            KernelError::CertificateRejected(p) => assert_eq!(p, proposition),
            _ => panic!("expected CertificateRejected"),
        }
    }

    /// Test 7: Transitivity — x = y and y = z → x = z
    #[test]
    fn test_check_trans() {
        let mut ctx = LocalContext::new();
        let checker = make_checker();

        let h1_id = ctx.add_hypothesis(Proposition::eq(v("x"), v("y")));
        let h2_id = ctx.add_hypothesis(Proposition::eq(v("y"), v("z")));

        let proof = Proof::Trans(
            Box::new(Proof::Hypothesis(h1_id)),
            Box::new(Proof::Hypothesis(h2_id)),
        );
        let expected = Proposition::eq(v("x"), v("z"));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 8: Transitivity — with reflexivity (x = x and x = y → x = y)
    #[test]
    fn test_check_trans_with_refl() {
        let mut ctx = LocalContext::new();
        let checker = make_checker();

        let h_id = ctx.add_hypothesis(Proposition::eq(v("x"), v("y")));

        let proof = Proof::Trans(
            Box::new(Proof::Refl(v("x"))),
            Box::new(Proof::Hypothesis(h_id)),
        );
        let expected = Proposition::eq(v("x"), v("y"));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 9: Congruence — x = y → sin(x) = sin(y)
    #[test]
    fn test_check_congr_sin() {
        let mut ctx = LocalContext::new();
        let checker = make_checker();

        let h_id = ctx.add_hypothesis(Proposition::eq(v("x"), v("y")));

        let proof = Proof::Congr {
            constructor: ExprConstructor::Sin,
            arg_proofs: vec![Proof::Hypothesis(h_id)],
        };
        let expected = Proposition::eq(Sin(Box::new(v("x"))), Sin(Box::new(v("y"))));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 10: Congruence — x = y → sqrt(x²) = sqrt(y²)
    #[test]
    fn test_check_congr_sqrt() {
        let mut ctx = LocalContext::new();
        let checker = make_checker();

        let h_id = ctx.add_hypothesis(Proposition::eq(v("x"), v("y")));

        let proof = Proof::Congr {
            constructor: ExprConstructor::Sqrt,
            arg_proofs: vec![Proof::Hypothesis(h_id.clone())],
        };
        // Wait, sqrt(x) = sqrt(y) not sqrt(x²) = sqrt(y²).
        // Let me fix: we want sqrt(x) = sqrt(y) from x = y.
        let expected = Proposition::eq(Sqrt(Box::new(v("x"))), Sqrt(Box::new(v("y"))));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 11: Congruence — x = y and a = b → x + a = y + b
    #[test]
    fn test_check_congr_add_binary() {
        let mut ctx = LocalContext::new();
        let checker = make_checker();

        let h1_id = ctx.add_hypothesis(Proposition::eq(v("x"), v("y")));
        let h2_id = ctx.add_hypothesis(Proposition::eq(v("a"), v("b")));

        let proof = Proof::Congr {
            constructor: ExprConstructor::Add,
            arg_proofs: vec![Proof::Hypothesis(h1_id), Proof::Hypothesis(h2_id)],
        };
        let expected = Proposition::eq(v("x") + v("a"), v("y") + v("b"));

        assert!(checker.check(&ctx, &proof, &expected).is_ok());
    }

    /// Test 12: Congruence — wrong arity
    #[test]
    fn test_check_congr_wrong_arity() {
        let ctx = LocalContext::new();
        let checker = make_checker();

        let proof = Proof::Congr {
            constructor: ExprConstructor::Sin, // expects 1 arg
            arg_proofs: vec![],                // but we give 0
        };
        let expected = Proposition::eq(v("x"), v("x"));

        let result = checker.check(&ctx, &proof, &expected);
        assert!(result.is_err());
        match result.unwrap_err() {
            KernelError::ConstructorArityMismatch { .. } => {} // ok
            other => panic!("expected ConstructorArityMismatch, got: {:?}", other),
        }
    }

    // ── Theorem Instantiation Tests ──────────────────────────

    /// Test 13: Apply add_zero theorem
    #[test]
    fn test_check_theorem_add_zero() {
        reset_fresh_counter();
        let checker = make_checker();
        let ctx = LocalContext::new();

        let theorem = checker.theorem_env.get_by_name("add_zero").unwrap();

        // Goal: (y + 0) = y
        let goal = Proposition::eq(v("y") + num(0.0), v("y"));

        // Apply theorem to get a proof
        let apply_result = apply_theorem(theorem, &goal).unwrap();

        // Construct proof: theorem with empty premises and subst {x → y}
        let mut subst = Substitution::new();
        subst.insert("x".to_string(), v("y"));

        let proof = Proof::Theorem {
            id: theorem.id,
            subst,
            premise_proofs: vec![], // no premises
        };

        assert!(checker.check(&ctx, &proof, &goal).is_ok());
    }

    /// Test 14: Apply theorem with uninstantiated binder → error
    #[test]
    fn test_check_theorem_missing_binder() {
        let checker = make_checker();
        let ctx = LocalContext::new();

        let theorem = checker.theorem_env.get_by_name("add_zero").unwrap();

        let proof = Proof::Theorem {
            id: theorem.id,
            subst: Substitution::new(), // empty — missing binder "x"
            premise_proofs: vec![],
        };
        let goal = Proposition::eq(v("y") + num(0.0), v("y"));

        let result = checker.check(&ctx, &proof, &goal);
        assert!(result.is_err());
        match result.unwrap_err() {
            KernelError::UninstantiatedBinder(name) => assert_eq!(name, "x"),
            other => panic!("expected UninstantiatedBinder, got: {:?}", other),
        }
    }

    // ── THE KEY TEST: Symbolic sqrt proof by hand ────────────

    /// THE KEY TEST: Hand-construct a proof of sqrt(y²) = y using
    /// the sqrt_square_nonnegative theorem and a hypothesis y ≥ 0.
    ///
    /// Theorem: ∀x, x ≥ 0 → sqrt(x²) = x   (sqrt_square_nonnegative)
    /// Context: hy: y ≥ 0
    /// Goal:    sqrt(y²) = y
    ///
    /// Proof:
    ///   1. Apply sqrt_square_nonnegative with {x → y}
    ///      → premise: y ≥ 0
    ///   2. Use hypothesis hy to discharge the premise
    #[test]
    fn test_check_sqrt_proof_symbolic() {
        reset_fresh_counter();
        let checker = make_checker();

        // Context: y ≥ 0
        let mut ctx = LocalContext::new();
        let hy_id = ctx.add_hypothesis(Proposition::ge(v("y"), num(0.0)));

        // Goal: sqrt(y²) = y
        let goal = Proposition::eq(
            Sqrt(Box::new(Pow(Box::new(v("y")), Box::new(num(2.0))))),
            v("y"),
        );

        let theorem = checker
            .theorem_env
            .get_by_name("sqrt_square_nonnegative")
            .unwrap();

        // Build the substitution: x → y
        let mut subst = Substitution::new();
        subst.insert("x".to_string(), v("y"));

        // Construct the proof
        let proof = Proof::Theorem {
            id: theorem.id,
            subst,
            premise_proofs: vec![
                // Premise proof: y ≥ 0 (from hypothesis)
                Proof::Hypothesis(hy_id),
            ],
        };

        let result = checker.check(&ctx, &proof, &goal);
        if let Err(ref e) = result {
            panic!("Proof check failed: {}", e);
        }
        assert!(result.is_ok());
    }

    /// Test 16: Theorem application with certificate premise
    ///
    /// If we have `∀x, x ≥ 0 → sqrt(x²) = x` and the goal is
    /// `sqrt(4²) = 4`, then:
    ///   - subst: x → 4
    ///   - premise: 4 ≥ 0
    ///   - premise proof: Certificate(ConstantEvaluation)
    #[test]
    fn test_check_sqrt_proof_numeric() {
        reset_fresh_counter();
        let checker = make_checker();
        let ctx = LocalContext::new();

        let goal = Proposition::eq(
            Sqrt(Box::new(Pow(Box::new(num(4.0)), Box::new(num(2.0))))),
            num(4.0),
        );

        let theorem = checker
            .theorem_env
            .get_by_name("sqrt_square_nonnegative")
            .unwrap();

        let mut subst = Substitution::new();
        subst.insert("x".to_string(), num(4.0));

        let proof = Proof::Theorem {
            id: theorem.id,
            subst,
            premise_proofs: vec![Proof::Certificate {
                proposition: Proposition::ge(num(4.0), num(0.0)),
                certificate: Certificate::ConstantEvaluation,
            }],
        };

        let result = checker.check(&ctx, &proof, &goal);
        if let Err(ref e) = result {
            panic!("Proof check failed: {}", e);
        }
        assert!(result.is_ok());
    }

    /// Test 17: Theorem with wrong premise proof → should fail
    #[test]
    fn test_check_theorem_wrong_premise() {
        reset_fresh_counter();
        let checker = make_checker();

        let mut ctx = LocalContext::new();
        let hy_id = ctx.add_hypothesis(Proposition::ge(v("y"), num(0.0)));

        // Goal: sqrt(y²) = y
        let goal = Proposition::eq(
            Sqrt(Box::new(Pow(Box::new(v("y")), Box::new(num(2.0))))),
            v("y"),
        );

        let theorem = checker
            .theorem_env
            .get_by_name("sqrt_square_nonnegative")
            .unwrap();

        let mut subst = Substitution::new();
        subst.insert("x".to_string(), v("y"));

        // Wrong premise proof: we provide a hypothesis x = 0 instead of y ≥ 0
        let proof = Proof::Theorem {
            id: theorem.id,
            subst,
            premise_proofs: vec![
                Proof::Hypothesis(hy_id), // This proves y ≥ 0, correct
                                          // Wait, we only have one premise and we provide one proof.
                                          // Let me make it wrong by using a different hypothesis.
            ],
        };

        // Actually, let's make a different test: use a hypothesis that
        // doesn't match the premise. We'll add a hypothesis x = 0 and
        // try to use it to prove y ≥ 0.
        let mut ctx2 = LocalContext::new();
        ctx2.add_hypothesis(Proposition::eq(v("x"), num(0.0)));

        let proof2 = Proof::Theorem {
            id: theorem.id,
            subst: {
                let mut s = Substitution::new();
                s.insert("x".to_string(), v("y"));
                s
            },
            premise_proofs: vec![
                Proof::Hypothesis(HypothesisId(1)), // This proves x = 0, NOT y ≥ 0
            ],
        };

        let result = checker.check(&ctx2, &proof2, &goal);
        assert!(result.is_err());
    }

    /// Test 18: Intro (implication introduction) — P ⊢ Q → ⊢ P → Q
    #[test]
    fn test_check_intro_implies() {
        let checker = make_checker();

        // Start with empty context
        let ctx = LocalContext::new();

        // Build proof: assume P, then use hypothesis to prove P
        let p = Proposition::eq(v("x"), num(0.0));

        let proof = Proof::Intro {
            binder: Binder::Assumption {
                hypothesis_id: HypothesisId(1), // arbitrary, kernel generates its own
                proposition: Box::new(p.clone()),
            },
            body: Box::new(Proof::Hypothesis(HypothesisId(1))),
        };

        let expected = Proposition::implies(p.clone(), p.clone());

        let result = checker.check(&ctx, &proof, &expected);
        if let Err(ref e) = result {
            panic!("Proof check failed: {}", e);
        }
        assert!(result.is_ok());
    }

    /// Test 19: Intro (universal introduction) — ⊢ P(x) → ⊢ ∀x, P(x)
    #[test]
    fn test_check_intro_forall() {
        let checker = make_checker();
        let ctx = LocalContext::new();

        // Prove: ∀x, x = x
        let proof = Proof::Intro {
            binder: Binder::ForAll {
                variable: crate::proposition::shared_var("x"),
            },
            body: Box::new(Proof::Refl(v("x"))),
        };

        let expected = forall_v("x", Proposition::eq(v("x"), v("x")));

        let result = checker.check(&ctx, &proof, &expected);
        if let Err(ref e) = result {
            // The error might just be VarId mismatch even though the display is identical
            let actual = checker.check_inner(&ctx, &proof).unwrap();
            assert_eq!(
                format!("{}", actual),
                format!("{}", expected),
                "Proof check failed: expected {}, got {}",
                expected,
                actual
            );
        }
        assert!(result.is_ok());
    }

    /// Test 20: Intro (universal) with variable appearing in hypothesis → fail
    #[test]
    fn test_check_intro_forall_clash() {
        let checker = make_checker();

        let mut ctx = LocalContext::new();
        ctx.add_hypothesis(Proposition::ge(v("x"), num(0.0))); // x appears in hypothesis

        // Try to prove: ∀x, x = x — but x is free in hypothesis!
        let proof = Proof::Intro {
            binder: Binder::ForAll {
                variable: crate::algebra::Variable::named("x"),
            },
            body: Box::new(Proof::Refl(v("x"))),
        };

        let expected = forall_v("x", Proposition::eq(v("x"), v("x")));

        let result = checker.check(&ctx, &proof, &expected);
        assert!(result.is_err());
        match result.unwrap_err() {
            KernelError::IntroArbitraryClash { .. } => {} // ok
            other => panic!("expected IntroArbitraryClash, got: {:?}", other),
        }
    }

    /// Test 21: Full chain — trans + theorem + cert
    ///
    /// Prove: sqrt(4²) = 4 using sqrt_square_nonnegative + 4 ≥ 0
    ///
    /// Hand-constructed proof:
    ///   1. Theorem sqrt_square_nonnegative with {x → 4}
    ///      → premise: 4 ≥ 0
    ///   2. Certificate: 4 ≥ 0 (constant evaluation)
    #[test]
    fn test_check_full_chain() {
        reset_fresh_counter();
        let checker = make_checker();
        let ctx = LocalContext::new();

        let goal = Proposition::eq(
            Sqrt(Box::new(Pow(Box::new(num(4.0)), Box::new(num(2.0))))),
            num(4.0),
        );

        let theorem = checker
            .theorem_env
            .get_by_name("sqrt_square_nonnegative")
            .unwrap();

        let mut subst = Substitution::new();
        subst.insert("x".to_string(), num(4.0));

        // Hand-construct the proof
        let proof = Proof::Theorem {
            id: theorem.id,
            subst,
            premise_proofs: vec![Proof::Certificate {
                proposition: Proposition::ge(num(4.0), num(0.0)),
                certificate: Certificate::ConstantEvaluation,
            }],
        };

        let result = checker.check(&ctx, &proof, &goal);
        assert!(result.is_ok(), "Full chain proof should pass: {:?}", result);
    }

    /// Test 22: ProofChecker rejects a bad proof
    #[test]
    fn test_check_rejects_bad_proof() {
        let checker = make_checker();
        let ctx = LocalContext::new();

        // Try to prove x = y from nothing
        let proof = Proof::Refl(v("x"));
        let expected = Proposition::eq(v("x"), v("y"));

        assert!(checker.check(&ctx, &proof, &expected).is_err());
    }

    /// Test 23: Theorem with wrong theorem ID
    #[test]
    fn test_check_theorem_wrong_id() {
        let checker = make_checker();
        let ctx = LocalContext::new();

        let proof = Proof::Theorem {
            id: TheoremId(999), // doesn't exist
            subst: Substitution::new(),
            premise_proofs: vec![],
        };
        let expected = Proposition::eq(v("x"), v("x"));

        let result = checker.check(&ctx, &proof, &expected);
        assert!(result.is_err());
        match result.unwrap_err() {
            KernelError::NoSuchTheorem(id) => assert_eq!(id, TheoremId(999)),
            other => panic!("expected NoSuchTheorem, got: {:?}", other),
        }
    }
}
